Repository Xghayor/Recipe-craft, pull requests merged in 2024-02, with the labels that each got.

#17 Milestone 6: Add recipe list page
  app/controllers/public_recipes_controller.rb
  app/controllers/recipes_controller.rb
  app/models/ability.rb
  app/models/recipe.rb
  app/models/user.rb
  app/views/public_recipes/index.html.erb
  app/views/recipes/index.html.erb
  app/views/recipes/show.html.erb
  app/views/users/index.html.erb
  config/routes.rb
  db/migrate/20231011053225_create_recipes.rb
  db/schema.rb
Labels: authorization

#18 Milestone 7: Recipe detail
  app/controllers/recipes_controller.rb
  app/views/recipes/index.html.erb
  app/views/recipes/show.html.erb
Labels: authorization

#19 Milestone 8: Navigation menu
  app/assets/stylesheets/application.css
  app/controllers/foods_controller.rb
  app/controllers/public_recipes_controller.rb
  app/controllers/recipes_controller.rb
  app/controllers/shopping_lists_controller.rb
  app/models/ability.rb
  app/models/recipe.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/layouts/_navigation.html.erb
  app/views/layouts/application.html.erb
  app/views/public_recipes/index.html.erb
  app/views/recipes/show.html.erb
  app/views/users/index.html.erb
  config/routes.rb
  db/migrate/20231011053225_create_recipes.rb
  db/schema.rb
Labels: enhancement, ui/ux

#20 Milestone 9: Add rspec and integration specs
  .gitattributes
  .gitignore
  .ruby-version
  .stylelintrc.json
  Gemfile
  Gemfile.lock
  LICENSE
  Rakefile
  app/controllers/foods_controller.rb
  app/controllers/users_controller.rb
  app/models/food.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/foods/index.html.erb
  app/views/foods/new.html.erb
  app/views/layouts/_navigation.html.erb
  app/views/users/index.html.erb
  config/environments/test.rb
  db/schema.rb
  package-lock.json
  spec/integrations/food_index_spec.rb
  spec/integrations/food_new_spec.rb
  spec/integrations/public_recipes_index_spec.rb
  spec/integrations/recipe_foods_new_spec.rb
  spec/integrations/recipe_index_spec.rb
  spec/integrations/recipes_new_spec.rb
  spec/integrations/recipes_show_spec.rb
  spec/integrations/shopping_lists_index_spec.rb
  spec/models/food_spec.rb
  spec/models/recipe_food_spec.rb
  spec/models/recipe_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/foods_spec.rb
  spec/requests/public_recipes_spec.rb
  spec/requests/recipe_foods_spec.rb
  spec/requests/recipes_spec.rb
  spec/requests/shopping_lists_spec.rb
  spec/requests/users_spec.rb
Labels: integration-test, unit-test

#21 Milestone 10: Eager loading
  app/assets/images/food.jpg
  app/assets/stylesheets/application.css
  app/assets/stylesheets/foods.css
  app/assets/stylesheets/public_recipes.css
  app/assets/stylesheets/recipes.css
  app/assets/stylesheets/users.css
  app/controllers/foods_controller.rb
  app/controllers/recipe_foods_controller.rb
  app/controllers/recipes_controller.rb
  app/views/devise/passwords/edit.html.erb
  app/views/foods/index.html.erb
  app/views/foods/new.html.erb
  app/views/layouts/_navigation.html.erb
  app/views/layouts/application.html.erb
  app/views/public_recipes/index.html.erb
  app/views/recipe_foods/new.html.erb
  app/views/recipes/index.html.erb
  app/views/recipes/new.html.erb
  app/views/recipes/show.html.erb
  app/views/shopping_lists/index.html.erb
  app/views/users/index.html.erb
  bin/bundle
  bin/importmap
  bin/rails
  bin/rake
  bin/setup
  package-lock.json
  spec/integrations/recipe_index_spec.rb
  spec/integrations/recipes_show_spec.rb
Labels: enhancement, performance
