Repository Xghayor/Recipe-craft, pull requests merged in 2024-01, with the labels that each got.

#12 Milestone 1: Technical setup
  .github/workflows/linters.yml
  .gitignore
  .rspec
  .rubocop.yml
  .stylelintrc.json
  Gemfile
  Gemfile.lock
  Rakefile
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  app/mailers/application_mailer.rb
  app/models/ability.rb
  app/models/user.rb
  bin/bundle
  bin/importmap
  bin/rails
  bin/rake
  bin/setup
  config.ru
  config/application.rb
  config/boot.rb
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/importmap.rb
  config/initializers/assets.rb
  config/initializers/content_security_policy.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/initializers/permissions_policy.rb
  config/puma.rb
  config/routes.rb
  db/migrate/20240129181521_create_users.rb
  db/migrate/20240129181705_create_recipes.rb
  db/migrate/20240129181853_create_foods.rb
  db/migrate/20240129182033_create_recipe_foods.rb
  db/migrate/20240129184149_add_devise_to_users.rb
  db/migrate/20240129192021_add_confirmable_fields_to_users.rb
  db/schema.rb
  db/seeds.rb
  package-lock.json
  package.json
  spec/rails_helper.rb
  spec/spec_helper.rb
  test/application_system_test_case.rb
  test/channels/application_cable/connection_test.rb
  test/controllers/foods_controller_test.rb
  test/controllers/recipes_controller_test.rb
  test/controllers/users_controller_test.rb
  test/models/food_test.rb
  test/models/recipe_food_test.rb
  test/models/recipe_test.rb
  test/models/user_test.rb
  test/test_helper.rb
Labels: project-setup

#13 Milestone 2: Login and registration page
  app/controllers/users_controller.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/mailer.html.erb
  app/views/users/index.html.erb
  config/database.yml
  config/routes.rb
  spec/helpers/users_helper_spec.rb
  spec/models/user_spec.rb
  spec/requests/users_spec.rb
Labels: authentication

#15 Milestone 4: Add foods page
  app/controllers/application_controller.rb
  app/controllers/foods_controller.rb
  app/controllers/recipes_controller.rb
  app/helpers/foods_helper.rb
  app/models/ability.rb
  app/models/food.rb
  app/models/recipe.rb
  app/models/user.rb
  app/views/foods/index.html.erb
  app/views/foods/new.html.erb
  app/views/recipes/index.html.erb
  app/views/recipes/show.html.erb
  app/views/users/index.html.erb
  bin/bundle
  bin/importmap
  bin/rails
  bin/rake
  bin/setup
  config/application.rb
  config/boot.rb
  config/credentials.yml.enc
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/importmap.rb
  config/initializers/assets.rb
  config/initializers/content_security_policy.rb
  config/initializers/devise.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/initializers/permissions_policy.rb
  config/locales/en.yml
  config/puma.rb
  config/routes.rb
  db/migrate/20231010095026_devise_create_users.rb
  db/migrate/20231010095649_add_name_role_to_users.rb
  db/migrate/20231011053225_create_recipes.rb
  db/migrate/20231011055251_add_users_ref_to_recipes.rb
  db/migrate/20231012034612_create_foods.rb
  db/migrate/20231012034700_add_users_ref_to_foods.rb
  db/schema.rb
  db/seeds.rb
  spec/helpers/foods_helper_spec.rb
  spec/helpers/recipes_helper_spec.rb
  spec/models/food_spec.rb
  spec/requests/foods_spec.rb
  spec/requests/recipes_spec.rb
  test/channels/application_cable/connection_test.rb
  test/test_helper.rb
Labels: authorization
